endpoint: wss://bifrost-polkadot.ibp.network
mock-signature-host: true
block: ${env.BIFROST_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5
port: 3423

import-storage:
  System:
    Account:
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
        - providers: 1
          data:
            free: 1000000000000000

  Tokens:
    Accounts:
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: ASG
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: BNC
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: KUSD
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: DOT
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: KSM
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: ETH
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: KAR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: ZLK
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: PHA
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: RMRK
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token: MOVR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 0 # DOT
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 1 # GLMR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 2 # USDT
        - free: '100000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 3 # ASTR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 4 # FIL  (Filecoin)
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 5 # USDC
        - free: '100000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 6 # interBTC (iBTC) from Interlay
        - free: '2100000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 7 # INTR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 8 # MANTA
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 9 # BNCs (inscriptions on BNC)
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 10 # PINK
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - Token2: 11 # DED
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - VToken2: 0 # vDOT
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - VToken2: 1 # vGLMR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - VToken2: 3 # vASTR
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - VToken2: 4 # vFIL
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - VToken2: 8 # vMANTA
        - free: '1000000000000000'
      -
        -
          - 5DPLGAR43FRbPxkkAWJudfyLTbJAP1GMvtyt1mx7KCuiuNvK
          - VSToken2: 0 # vsDOT
        - free: '1000000000000000'