endpoint: 
- wss://polkadot-asset-hub-rpc.polkadot.io
- wss://sys.ibp.network/statemint
- wss://sys.dotters.network/statemint
- wss://sys.ibp.network/asset-hub-polkadot
- wss://sys.dotters.network/asset-hub-polkadot
- wss://asset-hub-polkadot-rpc.dwellir.com
mock-signature-host: true
port: 3421

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 900000000 }]
      - [[21, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 900000000 }]
      - [[1337, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 900000000 }]
#    Asset: [[[21], { supply: 1000000000 }]]
